# Generated by Django 5.2.1 on 2025-06-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
