# Generated by Django 5.2.1 on 2025-06-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название категории'),
        ),
    ]
