# Generated by Django 5.2.1 on 2025-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер задачи'),
        ),
    ]
