# Generated by Django 5.2.1 on 2025-06-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер категории'),
        ),
    ]
